apiVersion: v1
kind: Service
metadata:
 namespace: webapp
 name: mysql-service
spec:
 selector:
  app: mariadb
 ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: mariadb-deployment
 namespace: webapp
 labels:
  app: mariadb
spec:
 replicas: 1
 selector:
  matchLabels:
   app: mariadb
 template:
  metadata:
   labels:
    app: mariadb
  spec:
   containers:
    - name: mariadb
      image: mariadb:latest
      ports:
       - containerPort: 3306
      volumeMounts:
       - name: mariadb-initial-configmap
         mountPath: /docker-entrypoint-initdb.d
       - mountPath: "/var/lib/mysql"
         subPath: "mysql"
         name: mariadb-data
      env:
       - name: MARIADB_ROOT_PASSWORD
         valueFrom:
          secretKeyRef:
           name: mariadb-secret
           key: mariadb_root_password
       - name: DB_USER
         valueFrom:
          secretKeyRef:
           name: mariadb-secret
           key: db_user
       - name: DB_PASSWORD
         valueFrom:
          secretKeyRef:
           name: mariadb-secret
           key: db_password
   volumes:
   - name: mariadb-configmap-volume
     configMap:
      name: mariadb-configmap
      items:
       - key: db-load-script.sql
         path: db-load-script.sql
   - name: mariadb-data
     persistentVolumeClaim:
      claimName: mariadb-pvc
