apiVersion: v1
data:
  db_name: ZWNvbWRi
  db_password: ZWNvbXBhc3N3b3Jk
  db_user: ZWNvbXVzZXI=
  mariadb_root_password: c2VjcmV0
kind: Secret
metadata:
  name: mariadb-secret
  namespace: webapp
type: Opaque
