apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  namespace: webapp
spec:
  storageClassName: managed
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
