apiVersion: v1
kind: Service
metadata:
 name: ecom-web-service
 namespace: webapp
spec:
 selector:
  app: ecom-web
 type: LoadBalancer
 ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
---

apiVersion: apps/v1
kind: Deployment
metadata:
 name: ecom-web
 namespace: webapp
 labels:
  app: ecom-web
spec:
 replicas: 1
 selector:
  matchLabels:
   app: ecom-web
 template:
  metadata:
   labels:
    app: ecom-web
  spec:
   containers:
    - name: ecom-web
      image: abbasahmedkhan.azurecr.io/web:v6
      imagePullPolicy: Always
      ports:
       - containerPort: 80
      env:
       - name: DB_HOST
         valueFrom:
          configMapKeyRef:
           name: web-configmap
           key: database_url
       - name: DB_USER
         valueFrom:
          secretKeyRef:
           name: mariadb-secret
           key: db_user
       - name: DB_PASSWORD
         valueFrom:
          secretKeyRef:
           name: mariadb-secret
           key: db_password
       - name: DB_NAME
         valueFrom:
          secretKeyRef:
           name: mariadb-secret
           key: db_name

