apiVersion: v1
kind: Service
metadata:
  name: ecom-db-service
  namespace: webapp
spec:
  selector:
    app: ecom-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-db-deployment
  namespace: webapp
  labels:
    app: ecom-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecom-db
  template:
    metadata:
      labels:
        app: ecom-db
    spec:
      nodeSelector:
        kubernetes.io/hostname: aks-agentpool-26827573-vmss000000
      containers:
      - name: ecomdb
        image: mariadb:latest
        env:
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ecom-db-secret
              key: mariadb-password
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ecom-db-secret
              key: mariadb-root-password
        - name: MARIADB_USER
          valueFrom:
            configMapKeyRef:
              name: ecom-db-config
              key: mariadb_user
        - name: MARIADB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: ecom-db-config
              key: mariadb_database
        volumeMounts:
          - name: ecom-db-config-vol
            mountPath: /docker-entrypoint-initdb.d
          - name: ecom-db-data-vol
            mountPath: /var/lib/mysql
      volumes:
      - name: ecom-db-config-vol
        configMap:
          name: ecom-db-config
          items:
            - key: db-load-script.sql
              path: db-load-script.sql
      - name: ecom-db-data-vol
        persistentVolumeClaim:
          claimName: ecom-db-pvc
