apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ecom-db-pvc
  namespace: webapp
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 1Gi
