apiVersion: v1
kind: Service
metadata:
  name: ecom-web-service
  namespace: webapp
spec:
  type: LoadBalancer
  selector:
    app: ecom-web
  ports:
    - protocol: TCP
      port: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-web-deployment
  namespace: webapp
  labels:
    app: ecom-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecom-web
  template:
    metadata:
      labels:
        app: ecom-web
    spec:
      containers:
      - name: ecom-web
        image: abbasahmed40.azurecr.io/ecom-web:v1 
        ports:
        - containerPort: 80
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ecom-web-secret
              key: db-password
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: ecom-web-config
              key: db_host
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: ecom-web-config
              key: db_user
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: ecom-web-config
              key: db_name
        
